### ISSUE TITLE
Both eula_slug and eula: { slug: 'foo'} are needed

### ISSUE THREAD

**Issue by ctaymor** [pivotal-cf-experimental/pivnet-resource#29] opened 2016-06-06 22:56 UTC
With the following specification of the eula slug in the metadata file, doing a put of the concourse resource, I get a 422 response. The resource is [currently swallowing errors](https://github.com/pivotal-cf-experimental/pivnet-resource/issues/28), so I don't have any error output to provide in this case. However, from intercepting the build, I can see that the 422 was the response from the POST to /api/v2/products/ops-manager/release

```
---
release:
  eula_slug: "some_valid_slug"
...
```

Trying with the exact same metadata via a curl request, I get an error of `{"status":422,"message":"validation errors creating release for product 'ops-manager'","errors":["EULA can't be blank"]}`.

If I provide the eula slug via the format specified in the [Pivnet API Docs](https://network.pivotal.io/docs/api#public/docs/api/v2/releases.md), the request succeeds with a curl request. However, when I use the same metadata 
```
---
release:
  eula:
    slug: "some_valid_slug"
...
```
in the resource, I get the following error in concourse:
```
...
Successfully pulled pivotalcf/pivnet-resource@sha256:....

logging to /tmp/pivnet-resource-out.log668910284
2016/06/06 21:11:49 metadata_file is invalid: missing required value "eula_slug"
```

However, if I provide BOTH formats, as below, the put to the pivnet resource succeeds, and everything works!

```
---
release:
  eula_slug: "some_valid_slug"
  eula:
    slug: "some_valid_slug"
```

This seems like a bug. Or if it is intended, it would great to specify in the docs that both are needed.

**Comment by robdimsdale** [comment] 2016-06-07 03:55
Thanks for reporting, @ctaymor - that's definitely not the intended behavior. We'll use this story to drive out the fix.

**Comment by zachgersh** [comment] 2016-06-14 15:17
@ctaymor so, I was slightly baffled as to how this would work, so I did some walking through the code.

If you have a look at this snippet:

We are actually ending up with the json you would expect (if not our POST to pivnet would fail). Adding the additional field to the metadata shouldn't have done anything because it does not get marshaled and would effectively just be discarded.

I am going to change the format of our metadata file so it corresponds to the format that is expected by the API instead of the weird `eula_slug

**Comment by ctaymor** [comment] 2016-06-14 17:32
@zachgersh and @robdimsdale I tried it again, and it seems that the 422 may have had some other source. Using this format in the metadata, I was able to successfully do the put with the resource. 

```
---
release:
...
  eula_slug: "pivotal_software_eula"
...
```

I'm not sure why we were getting a 422, since the errors were swallowed, but this doesn't seem to be the actual problem we were having.

**Comment by zachgersh** [comment] 2016-06-14 18:13
Thanks @ctaymor for trying again. I am going to close this but we will make the metadata file look more like your example of

```
---
release:
  eula:
    slug: "some_valid_slug"
...
```

This is easier to discover in general.

**Closed by zachgersh** 2016-06-14 18:13 UTC
Labels: in progress
