### ISSUE TITLE
README should warn users about switching away from eu-west-1

### ISSUE THREAD

**Issue by Manifaust** [pivotal-cf-experimental/pivnet-resource#16] opened 2016-03-24 20:32 UTC
If a developer tries to push a production release to a region that's not `eu-west-1` (the default), the `put` will fail with a non-obvious error. However, it's not clear why until I spoke with Tim and he gave me a possible business reason.

I tried using another region in the first place because I was debugging another error and was checking up on s3 using `us-east-1` during the whole process. I thought that switching to `us-east-1` might fix my problem but it turned out to create another problem (with the same error message).

**Comment by robdimsdale** [comment] 2016-03-24 22:58
@Manifaust sounds reasonable. Could you elaborate on the failure message that you received? And it sounds like you had some other issue initially - what was that? How did you resolve it?

As well as updating the README, are there more specific error messages (or output in general) that you would have wanted to see in the concourse UI and/or the pivnet resource logs?

We will update the README as part of the [auto-created tracker story for this issue](https://www.pivotaltracker.com/story/show/116327055), and if there are functional changes we could make, we'll create other stories for them too.

Thanks,
Rob

**Comment by Manifaust** [comment] 2016-03-28 18:54
@robdimsdale I'm not 100% sure but I believe the error we received by switching away from `eu-west-1` was:

```
logging to /tmp/pivnet-resource-out.log317182351
2016/03/23 22:18:27 Error running /opt/resource/s3-out: exit status 1
```

The other issue I had was that our AWS creds did not have `ls` permission. Tim helped us solve this. When a user's AWS creds does not have `ls` permission the pivnet-resource will also spit out the same error.

Ideally, it would be nice to see an error message that makes it clear there was a permission issue.

**Comment by robdimsdale** [comment] 2016-03-31 04:54
@Manifaust yes I agree a more clear error message would be desirable. When you received that error message, did you look in the logs for any more information? I assume that you can't reproduce this error as you've since fixed the infrastructure misconfiguration that was causing it?

Currently we shell out to the [concourse s3 resource](https://github.com/concourse/s3-resource) and add its output to our log file. Because this is a third-party dependency it is harder for us to modify the errors that it logs. We might actually already log more information; I've created the following story to see if we can improve the error messages returned to the concourse UI:

- [pivnet resource out should have better error messages when s3-out binary exits 1](https://www.pivotaltracker.com/story/show/116668253)

I also updated the README to clearly highlight the consistency requirement in various `source` configuration. It's on the [develop branch](https://github.com/pivotal-cf-experimental/pivnet-resource/tree/develop) and will be promoted to the [master branch](https://github.com/pivotal-cf-experimental/pivnet-resource/tree/master) with the next release.

Let me know if you think there is any other action you'd like to see us take, otherwise I'll close this issue.

Thanks,
Rob

**Comment by zachgersh** [comment] 2016-04-03 23:47
@Manifaust - assuming you are satisfied. Going to close this. Please feel free to open again!

**Closed by zachgersh** 2016-04-03 23:47 UTC
